<a href="https://colab.research.google.com/github/rayaanahmed46/MLwork-ray/blob/master/Assignment_1_DS(ray).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [0]:
import numpy as np
a = np.random.rand(3,5)
b = np.random.rand(3,5)
print(a)
print(b)

[[0.27819919 0.58837246 0.48843282 0.30780897 0.44617844]
 [0.73301601 0.25822407 0.59400644 0.88333854 0.63090623]
 [0.14671109 0.61358476 0.95659794 0.40140469 0.6153381 ]]
[[0.55721389 0.51541557 0.68616955 0.56624618 0.65511374]
 [0.12343542 0.80147801 0.67765421 0.3307414  0.14721677]
 [0.3039702  0.32524596 0.88123219 0.95909599 0.12463766]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all positive integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [1]:
import numpy as np
c=np.arange(100)
d=np.zeros((3,3),dtype=float)
print(c)
print(d)




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [2]:
e = [[1,2,3],[4,5,6],[7,8,9]]
f=np.array(e)
print(f)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [5]:
h=c.reshape(10,10)
c1=h.ravel()
if c.shape is c1.shape:print('YES')
else:print('NO')

NO


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [10]:
A = np.random.rand(2,10,5)
A1=np.transpose(A,(2,0,1))
print(A1)

[[[0.2157692  0.10410184 0.89670616 0.81355815 0.54257967 0.1079124
   0.83958691 0.90985536 0.41213114 0.59178689]
  [0.62044945 0.67972772 0.40764244 0.16447024 0.43508509 0.64380364
   0.33001858 0.42486518 0.53001349 0.94740013]]

 [[0.77529464 0.77300455 0.18127861 0.42965807 0.28837571 0.28208553
   0.08798485 0.78147713 0.45292748 0.66619483]
  [0.80520029 0.53986294 0.09933773 0.35176897 0.10468274 0.31512787
   0.733367   0.18639184 0.97755271 0.73187459]]

 [[0.13512671 0.09952614 0.65434211 0.04144078 0.91700053 0.85527661
   0.53319728 0.09828052 0.15674545 0.22491896]
  [0.02971331 0.35112598 0.93550713 0.43581297 0.42370642 0.02930307
   0.31930431 0.87500106 0.57557286 0.57880396]]

 [[0.55015218 0.17970876 0.18217464 0.23286327 0.03463785 0.8984217
   0.9550139  0.33605245 0.06634205 0.5377875 ]
  [0.95878331 0.49689231 0.50329162 0.24906656 0.49485681 0.61534148
   0.44570158 0.77079452 0.50626453 0.76283152]]

 [[0.50196696 0.01868885 0.55389691 0.31458562 0.36601888 

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [0]:
np.random.seed(0)
X = np.random.rand(10,5)
print()
print()
print()
print()
print()
print()



Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [0]:
np.random.seed(3)
Y = np.random.rand(10,10)




## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt


Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"



### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.